language: cpp
compiler:
  - clang
# Setup repos etc before installation
before_install:
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq

# Install dependencies
install:
  # install g++ 4.8, if tests are run with g++

  # install clang-3.5 if CPP14==1
  - sudo apt-get install --allow-unauthenticated -qq clang-3.5

  - cwd=$(pwd)

  # Install libc++ if tests are run with clang++
  - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk@201601 libcxx

  - cd libcxx/lib && bash buildit
  - sudo cp ./libc++.so.1.0 /usr/lib/
  - sudo mkdir /usr/include/c++/v1
  - cd .. && sudo cp -r include/* /usr/include/c++/v1/
  - cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so
  - sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd

  - CXX=clang++

# command to run tests
script:  
  - make -f makefile.mk all

notifications:
  slack: frenetiq:DQz0FZtCpcnrHkxQfEUNhdWI